path: []
inputs:
  evpnGatewayVteps: []
  tenants:
    - evpnMulticast: {}
      macVrfVniBase: 10000
      name: Internet_DC1
      vlanAwareBundles: []
      vlans: []
      vrfs:
        - additionalRouteTargets: []
          bgp: {}
          devices:
            - inputs:
                devices:
                  hostname: []
              tags:
                query: BORDER:DC1
            - inputs:
                devices:
                  hostname: []
              tags:
                query: STORAGE:DC1
          enableVrfIpVersion: {}
          evpnMulticast: {}
          externalBgpPeers: []
          iBgpDetails: {}
          l3Interfaces: []
          name: Internet
          natSourceDetails: {}
          overrideVariables: {}
          redistributeStaticRoutes: false
          staticRoutes: []
          vni: 1001
    - evpnMulticast: {}
      macVrfVniBase: 10000
      name: Internet_DC2
      vlanAwareBundles: []
      vlans: []
      vrfs:
        - additionalRouteTargets: []
          bgp: {}
          devices:
            - inputs:
                devices:
                  hostname: []
              tags:
                query: BORDER:DC2
            - inputs:
                devices:
                  hostname: []
              tags:
                query: STORAGE:DC2
          enableVrfIpVersion: {}
          evpnMulticast: {}
          externalBgpPeers: []
          iBgpDetails: {}
          l3Interfaces: []
          name: Internet
          natSourceDetails: {}
          overrideVariables: {}
          redistributeStaticRoutes: false
          staticRoutes: []
          vni: 1002
    - evpnMulticast: {}
      macVrfVniBase: 10000
      name: Internet_DC3
      vlanAwareBundles: []
      vlans: []
      vrfs:
        - additionalRouteTargets: []
          bgp: {}
          devices:
            - inputs:
                devices:
                  hostname: []
              tags:
                query: BORDER:DC3
            - inputs:
                devices:
                  hostname: []
              tags:
                query: STORAGE:DC3
          enableVrfIpVersion: {}
          evpnMulticast: {}
          externalBgpPeers: []
          iBgpDetails: {}
          l3Interfaces: []
          name: Internet
          natSourceDetails: {}
          overrideVariables: {}
          redistributeStaticRoutes: false
          staticRoutes: []
          vni: 1003
    - evpnMulticast: {}
      macVrfVniBase: 10000
      name: Internet_DC4
      vlanAwareBundles: []
      vlans: []
      vrfs:
        - additionalRouteTargets: []
          bgp: {}
          devices:
            - inputs:
                devices:
                  hostname: []
              tags:
                query: BORDER:DC4
            - inputs:
                devices:
                  hostname: []
              tags:
                query: STORAGE:DC4
          enableVrfIpVersion: {}
          evpnMulticast: {}
          externalBgpPeers: []
          iBgpDetails: {}
          l3Interfaces: []
          name: Internet
          natSourceDetails: {}
          overrideVariables: {}
          redistributeStaticRoutes: false
          staticRoutes: []
          vni: 1004
  vlanBasedMacVrfAttributeFormats:
    macVrfRouteDistinguisherFormat: Router-ID:VNI
    macVrfRouteTargetFormat: Upper-2B-ASN:VNI
  vrfAttributeFormats:
    vrfRouteDistinguisherFormat: Router-ID:VNI
    vrfRouteTargetFormat: Upper-2B-ASN:VNI
