path: []
inputs:
  hideAndShowProfiles:
    hideProperties:
      hideAclProperties: Hide
      hideDot1XProperties: Hide
      hideIgmpProperties: Hide
      hideIpLockingProperties: Hide
      hideIpSecProperties: Hide
      hideLoggingProperties: Hide
      hideMacSecProperties: Show
      hideMultiCastProprties: Hide
      hideMultiHomingProperties: Hide
      hidePoeProperties: Hide
      hidePortChannelProprties: Hide
      hidePortSecurityProperties: Hide
      hidePtpProperties: Hide
      hideQosProperties: Hide
      hideStormControlProperties: Hide
      natProperties: Hide
      taggingProperties: Hide
  macSecProfiles:
    - cipher: aes256-gcm
      devices:
        - inputs:
            deviceGroup:
              configureMacSecGlobally: true
          tags:
            query: 'BORDER:DC1 '
        - inputs:
            deviceGroup:
              configureMacSecGlobally: true
          tags:
            query: 'BORDER:DC2 '
        - inputs:
            deviceGroup:
              configureMacSecGlobally: true
          tags:
            query: 'BORDER:DC3 '
        - inputs:
            deviceGroup:
              configureMacSecGlobally: true
          tags:
            query: 'BORDER:DC4 '
      eapolMacDestination: null
      fips: false
      key: 0abc1234 7 1446405858517C7C7C
      l2ProtocolEthernetFlowControl: null
      l2ProtocolLldp: bypass unauthorized
      license: null
      macSecProfileName: Inter_DCI_MACSEC
      mkaSessionGroup:
        mkaReKeyPeriod: 30
      ptp: null
      replayProtection: null
      sak: {}
      trafficUnprotected: null
  profileOfProfiles:
    - aclIn: null
      aclOut: null
      dot1XProfile: null
      igmpProfile: null
      ipLockingProfile: null
      ipSecProfile: null
      loggingProfile: null
      macSecProfile: null
      multiHomingProfile: null
      natProfile: null
      pimProfile: null
      poeProfile: null
      portChannelProfile: null
      portSecurityProfile: null
      profileOfProfilesName: INTER_DCI_MACSEC_RTD
      ptpProfile: null
      qosInstance: null
      stormControlProfile: null
      taggingProfile: null
      v6AclIn: null
      v6AclOut: null
      vlanProfile: Routed_Port
  sites:
    - inputs:
        sitesGroup:
          devices:
            - inputs:
                devicesGroup:
                  all: all-switches
                  groupMemberNotation: stack-notation
                  hideAndShowOptions: {}
                  interfaceRanges:
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC2_LE01
                      enabled: true
                      esi: null
                      interfaceName: et2
                      ipPrefix: 205.206.192.32/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '1'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC2_LE02
                      enabled: true
                      esi: null
                      interfaceName: et2
                      ipPrefix: 205.206.192.34/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '2'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC3_LE01
                      enabled: true
                      esi: null
                      interfaceName: et5
                      ipPrefix: 205.206.192.40/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '1'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC3_LE02
                      enabled: true
                      esi: null
                      interfaceName: et5
                      ipPrefix: 205.206.192.42/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '2'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                  loopbackInterfaces: []
                  management0: Management0
                  management1: Management1
                  stack:
                    - inputs:
                        stackMember: '1'
                      tags:
                        query: device:SN-DC1LE01
                    - inputs:
                        stackMember: '2'
                      tags:
                        query: device:SN-DC1LE02
                  tunnelInterfaces: []
                  vlanInterfaces: []
                  vlans: []
              tags:
                query: BORDER:DC1
      tags:
        query: DC:DC1
    - inputs:
        sitesGroup:
          devices:
            - inputs:
                devicesGroup:
                  all: all-switches
                  groupMemberNotation: stack-notation
                  hideAndShowOptions: {}
                  interfaceRanges:
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC1_LE01
                      enabled: true
                      esi: null
                      interfaceName: et2
                      ipPrefix: 205.206.192.33/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '1'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC4_LE01
                      enabled: true
                      esi: null
                      interfaceName: et3
                      ipPrefix: 205.206.192.69/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '1'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC1_LE02
                      enabled: true
                      esi: null
                      interfaceName: et2
                      ipPrefix: 205.206.192.35/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '2'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC4_LE02
                      enabled: true
                      esi: null
                      interfaceName: et3
                      ipPrefix: 205.206.192.71/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '2'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                  loopbackInterfaces: []
                  management0: Management0
                  management1: Management1
                  stack:
                    - inputs:
                        stackMember: '1'
                      tags:
                        query: device:SN-DC2LE01
                    - inputs:
                        stackMember: '2'
                      tags:
                        query: device:SN-DC2LE02
                  tunnelInterfaces: []
                  vlanInterfaces: []
                  vlans: []
              tags:
                query: BORDER:DC2
      tags:
        query: DC:DC2
    - inputs:
        sitesGroup:
          devices:
            - inputs:
                devicesGroup:
                  all: all-switches
                  groupMemberNotation: stack-notation
                  hideAndShowOptions: {}
                  interfaceRanges:
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC4_LE01
                      enabled: true
                      esi: null
                      interfaceName: et4
                      ipPrefix: 205.206.192.97/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '1'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC1_LE01
                      enabled: true
                      esi: null
                      interfaceName: et5
                      ipPrefix: 205.206.192.41/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '1'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC4_LE02
                      enabled: true
                      esi: null
                      interfaceName: et4
                      ipPrefix: 205.206.192.99/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '2'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC1_LE02
                      enabled: true
                      esi: null
                      interfaceName: et5
                      ipPrefix: 205.206.192.43/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '2'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                  loopbackInterfaces: []
                  management0: Management0
                  management1: Management1
                  stack:
                    - inputs:
                        stackMember: '1'
                      tags:
                        query: device:SN-DC3LE01
                    - inputs:
                        stackMember: '2'
                      tags:
                        query: device:SN-DC3LE02
                  tunnelInterfaces: []
                  vlanInterfaces: []
                  vlans: []
              tags:
                query: BORDER:DC3
      tags:
        query: DC:DC3
    - inputs:
        sitesGroup:
          devices:
            - inputs:
                devicesGroup:
                  all: all-switches
                  groupMemberNotation: stack-notation
                  hideAndShowOptions: {}
                  interfaceRanges:
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC2_LE01
                      enabled: true
                      esi: null
                      interfaceName: et3
                      ipPrefix: 205.206.192.68/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '1'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC3_LE01
                      enabled: true
                      esi: null
                      interfaceName: et4
                      ipPrefix: 205.206.192.96/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '1'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC2_LE02
                      enabled: true
                      esi: null
                      interfaceName: et3
                      ipPrefix: 205.206.192.70/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '2'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                    - accessVlan: null
                      autoPortChannelNumbering: false
                      channelGroup: null
                      defaultGw: null
                      description: TO_DC3_LE02
                      enabled: true
                      esi: null
                      interfaceName: et4
                      ipPrefix: 205.206.192.98/31
                      ipv6Prefix: null
                      lacpEnabled: null
                      memberNumberCollection:
                        - '2'
                      mlagEnabled: null
                      portChannelDescription: null
                      profileOfProfileName: INTER_DCI_MACSEC_RTD
                      speed: null
                      vlansAllowed: null
                      vrf: null
                  loopbackInterfaces: []
                  management0: Management0
                  management1: Management1
                  stack:
                    - inputs:
                        stackMember: '1'
                      tags:
                        query: device:SN-DC4LE01
                    - inputs:
                        stackMember: '2'
                      tags:
                        query: device:SN-DC4LE02
                  tunnelInterfaces: []
                  vlanInterfaces: []
                  vlans: []
              tags:
                query: BORDER:DC4
      tags:
        query: DC:DC4
  vlanProfiles:
    - allowedVlans: null
      bgpSessionTrackerName: null
      bpduFilterEnabled: false
      bpduGuardEnabled: false
      command: null
      dhcpHelpers: []
      enableDhcPOollector: false
      ipaddress: null
      l2SubInterfaceProperties: {}
      linkTracking: {}
      mode: routed
      name: Routed_Port
      nativeVlanId: 1
      phoneTrunk: null
      phoneVlanId: 0
      portFastEnabled: false
      profileDescription: null
      profileIpAddressVirtual: null
      reversePathForwardingMode: null
      rootGuardEnabled: false
      sflow: null
      speed: null
      virtualRouterMacAddress: null
      vlanName: null
      vlanTranslation: []
