path: []
inputs:
  campus:
    - inputs:
        campusPod:
          - inputs:
              accessPod:
                - inputs:
                    interfaces:
                      - inputs:
                          adapterDetails:
                            description: HOST1
                            mode: access
                            vlans:
                              vlans: '101'
                        tags:
                          query: interface:Ethernet7@SN-Campus-Pod-A-LEAF-1A
                      - inputs:
                          adapterDetails:
                            description: HOST2
                            enabled: 'Yes'
                            mode: access
                            portProfile: MLAG-PORT-CHANNEL
                            vlans:
                              vlans: '102'
                        tags:
                          query: interface:Ethernet8@SN-Campus-Pod-A-LEAF-1A
                      - inputs:
                          adapterDetails:
                            description: HOST2
                            enabled: 'Yes'
                            mode: access
                            portProfile: MLAG-PORT-CHANNEL
                            vlans:
                              vlans: '102'
                        tags:
                          query: interface:Ethernet8@SN-Campus-Pod-A-LEAF-1B
                  tags:
                    query: Access-Pod:1
                - inputs:
                    interfaces:
                      - inputs:
                          adapterDetails:
                            mode: access
                            vlans:
                              vlans: '103'
                        tags:
                          query: interface:Ethernet7@SN-Campus-Pod-A-LEAF-2A
                  tags:
                    query: Access-Pod:2
                - inputs:
                    interfaces:
                      - inputs:
                          adapterDetails:
                            description: HOST4 and HOST5
                            portProfile: TRUNK
                        tags:
                          query: interface:Ethernet3@SN-Campus-Pod-A-LEAF-3C
                      - inputs:
                          adapterDetails:
                            mode: access
                            vlans:
                              vlans: '104'
                        tags:
                          query: interface:Ethernet3@SN-Campus-Pod-A-LEAF-3E
                  tags:
                    query: Access-Pod:3
            tags:
              query: Campus-Pod:A
          - inputs:
              accessPod:
                - inputs:
                    interfaces:
                      - inputs:
                          adapterDetails:
                            description: HOST1
                            mode: access
                            vlans:
                              vlans: '205'
                        tags:
                          query: interface:Ethernet7@SN-Campus-Pod-B-LEAF-1A
                      - inputs:
                          adapterDetails:
                            description: HOST2
                            enabled: 'Yes'
                            mode: access
                            portProfile: MLAG-PORT-CHANNEL
                            vlans:
                              vlans: '206'
                        tags:
                          query: interface:Ethernet8@SN-Campus-Pod-B-LEAF-1A
                      - inputs:
                          adapterDetails:
                            description: HOST2
                            enabled: 'Yes'
                            portProfile: MLAG-PORT-CHANNEL
                        tags:
                          query: interface:Ethernet8@SN-Campus-Pod-B-LEAF-1B
                  tags:
                    query: Access-Pod:1
                - inputs:
                    interfaces:
                      - inputs:
                          adapterDetails:
                            description: HOST3
                            mode: access
                            vlans:
                              vlans: '204'
                        tags:
                          query: interface:Ethernet7@SN-Campus-Pod-B-LEAF-2A
                  tags:
                    query: Access-Pod:2
                - inputs:
                    interfaces:
                      - inputs:
                          adapterDetails:
                            description: HOST4 AND HOST5
                            enabled: 'Yes'
                            portProfile: TRUNK
                        tags:
                          query: interface:Ethernet3@SN-Campus-Pod-B-LEAF-3C
                      - inputs:
                          adapterDetails:
                            description: HOST6
                            mode: access
                            vlans:
                              vlans: '206'
                        tags:
                          query: interface:Ethernet3@SN-Campus-Pod-B-LEAF-3E
                  tags:
                    query: Access-Pod:3
            tags:
              query: Campus-Pod:B
      tags:
        query: Campus:L2-CAMPUS
  portProfiles:
    - description: null
      dot1x: {}
      enabled: 'Yes'
      eosCli: null
      flowControl: {}
      mode: access
      name: MLAG-PORT-CHANNEL
      parentProfile: null
      phone: {}
      poe: {}
      portChannel:
        mlag: 'Yes'
        portChannelEnabled: 'Yes'
        portChannel: 'Yes'
        portChannelMode: active
      ptp: {}
      qosProfile: null
      spanningTree: {}
      speed: null
      stormControl: {}
      vlans: {}
    - description: TRUNK
      dot1x: {}
      enabled: 'Yes'
      eosCli: null
      flowControl: {}
      mode: trunk
      name: TRUNK
      parentProfile: null
      phone: {}
      poe: {}
      portChannel: {}
      ptp: {}
      qosProfile: null
      spanningTree: {}
      speed: null
      stormControl: {}
      vlans: {}
