path: []
inputs:
  campus:
    - inputs:
        campusPod:
          - inputs:
              accessPod:
                - inputs:
                    interfaces:
                      - inputs:
                          adapterDetails:
                            description: BLUE HOST A
                            mode: access
                            portProfile: PORT-CHANNEL
                            spanningTree: {}
                            vlans:
                              vlans: '101'
                        tags:
                          query: interface:Ethernet7@SN-Campus-Pod-A-LEAF1
                      - inputs:
                          adapterDetails:
                            description: ORANGE HOST B
                            mode: access
                            portProfile: PORT-CHANNEL
                            spanningTree: {}
                            vlans:
                              vlans: '102'
                        tags:
                          query: interface:Ethernet8@SN-Campus-Pod-A-LEAF1
                      - inputs:
                          adapterDetails:
                            description: ORANGE HOST B
                            mode: access
                            portProfile: PORT-CHANNEL
                            spanningTree: {}
                            vlans:
                              vlans: '102'
                        tags:
                          query: interface:Ethernet8@SN-Campus-Pod-A-LEAF2
                      - inputs:
                          adapterDetails:
                            description: BLUE HOST A
                            portProfile: PORT-CHANNEL
                            spanningTree: {}
                            vlans:
                              vlans: '101'
                        tags:
                          query: interface:Ethernet7@SN-Campus-Pod-A-LEAF2
                  tags:
                    query: Access-Pod:1
                - inputs:
                    interfaces:
                      - inputs:
                          adapterDetails:
                            description: HOST-C-ORANGE
                            mode: access
                            vlans:
                              vlans: '103'
                        tags:
                          query: interface:Ethernet7@SN-Campus-Pod-A-LEAF3
                  tags:
                    query: Access-Pod:2
                - inputs:
                    interfaces:
                      - inputs:
                          adapterDetails:
                            description: HOST-L PURPLE
                            mode: access
                            vlans:
                              vlans: '101'
                        tags:
                          query: interface:Ethernet3@SN-Campus-Pod-A-SW1
                      - inputs:
                          adapterDetails:
                            description: HOST-E-ORANGE
                            mode: access
                            vlans:
                              vlans: '102'
                        tags:
                          query: interface:Ethernet3@SN-Campus-Pod-A-SW2
                      - inputs:
                          adapterDetails:
                            description: HOST-F-RED
                            mode: access
                            vlans:
                              vlans: '104'
                        tags:
                          query: interface:Ethernet3@SN-Campus-Pod-A-SW3
                  tags:
                    query: Access-Pod:3
            tags:
              query: Campus-Pod:A
          - inputs:
              accessPod:
                - inputs:
                    interfaces:
                      - inputs:
                          adapterDetails:
                            description: HOST-G-GREEN
                            mode: access
                            portProfile: PORT-CHANNEL
                            vlans:
                              vlans: '205'
                        tags:
                          query: interface:Ethernet7@SN-Campus-Pod-B-LEAF1
                      - inputs:
                          adapterDetails:
                            description: HOST-G-GREEN
                            mode: access
                            portProfile: PORT-CHANNEL
                            vlans:
                              vlans: '205'
                        tags:
                          query: interface:Ethernet7@SN-Campus-Pod-B-LEAF2
                      - inputs:
                          adapterDetails:
                            description: HOST-H-PURPLE
                            mode: access
                            portProfile: PORT-CHANNEL
                            vlans:
                              vlans: '206'
                        tags:
                          query: interface:Ethernet8@SN-Campus-Pod-B-LEAF1
                      - inputs:
                          adapterDetails:
                            description: HOST-H-PURPLE
                            mode: access
                            portProfile: PORT-CHANNEL
                            vlans:
                              vlans: '206'
                        tags:
                          query: interface:Ethernet8@SN-Campus-Pod-B-LEAF2
                  tags:
                    query: Access-Pod:1
                - inputs:
                    interfaces:
                      - inputs:
                          adapterDetails:
                            description: HOST-I-RED
                            mode: access
                            vlans:
                              vlans: '204'
                        tags:
                          query: interface:Ethernet7@SN-Campus-Pod-B-LEAF3
                  tags:
                    query: Access-Pod:2
                - inputs:
                    interfaces:
                      - inputs:
                          adapterDetails:
                            description: HOST-J-BLUE
                            mode: access
                            vlans:
                              vlans: '201'
                        tags:
                          query: interface:Ethernet3@SN-Campus-Pod-B-SW1
                      - inputs:
                          adapterDetails:
                            description: HOST-K-ORANGE
                            mode: access
                            vlans:
                              vlans: '202'
                        tags:
                          query: interface:Ethernet3@SN-Campus-Pod-B-SW2
                      - inputs:
                          adapterDetails:
                            description: HOST-L-PURPLE
                            mode: access
                            vlans:
                              vlans: '206'
                        tags:
                          query: interface:Ethernet3@SN-Campus-Pod-B-SW3
                  tags:
                    query: Access-Pod:3
            tags:
              query: Campus-Pod:B
      tags:
        query: Campus:VXLAN-CAMPUS
  portProfiles:
    - description: PORT CHANNEL
      dot1x: {}
      enabled: null
      eosCli: null
      flowControl: {}
      mode: null
      name: PORT-CHANNEL
      parentProfile: null
      phone: {}
      poe: {}
      portChannel:
        description: PORT CHANNEL DESCR.
        mlag: 'Yes'
        portChannel: 'Yes'
        portChannelMode: active
      ptp: {}
      qosProfile: null
      spanningTree: {}
      speed: null
      stormControl: {}
      vlans: {}
